package com.dur.database.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


// default package
// Generated Mar 13, 2014 1:06:34 AM by Hibernate Tools 4.0.0

/**
 * TableName generated by hbm2java
 */
@Entity
@Table(name = "table_name")
public class TableName implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	private int id;
	
	@Column(name = "TEXT")
	private String text;
	
	@Column(name = "NUMBER")
	private Integer number;

	public TableName() {
	}

	public TableName(int id) {
		this.id = id;
	}

	public TableName(int id, String text, Integer number) {
		this.id = id;
		this.text = text;
		this.number = number;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
